### ISSUE TITLE
View User

### ISSUE THREAD

**Issue by twodayslate** [silverstripe-australia/silverstripe-memberprofiles#54]
This may seem dumb but how do you view a user's account? I see MemberProfileViewer_list.ss and MemberProfileViewer_view.ss but I don't know the URL to call those...

**Comment by TheBnl** [comment]
maybe you already figured this out, but for people the people with the same question. 
A profile can be viewed by navigating to: _urlparam/show/$ID_ (where _urlparam_ is the urlparam of the page you made with the MemberProfiles page type). In the file MemberProfilePage.php you can find all the allowed actions that are available.

**Comment by leclerc** [comment]
Another dumb question:
on MemberProfileViewer You are using $Me. I want to customize the profile page, how data is rendered, but I have a problem accessing fields by name  in "Sections" loop.

**Comment by rikisommers** [comment]
Hi
another possible dumb question.
my aim is to list all members in front end to public.
MemberProfileViewer_list plus custom field content, img's ect
is there a simple approach here?

**Comment by nyeholt** [comment]
@leclerc - the $Me variable in that context is an instance of "MemberProfileFieldsSection" - this output is rendered using the MemberProfileFieldsSection.ss template, or you should be able to access the $Member.FieldName variables within that <% loop Sections %> block. 

@rikisommers  - you can create your own version of the MemberProfileViewer_list.ss template - you'll likely need to add an extension to Member for adding your own fields in place though.

**Comment by leclerc** [comment]
TY nyeholt fot the answer, as usually it goes, shortly after posting the question I've found the solution ;)
