### ISSUE TITLE
If I try to use $renderWith($ClassName) it crashes.

### ISSUE THREAD

**Issue by liutaurasp** [silverstripe-australia/silverstripe-memberprofiles#91]
If I try to use $renderWith($ClassName) to create a one-page site I get the following error:
[User Warning] None of these templates can be found in theme 'test': MemberProfilePage.ss

Do you have any ideas how could I resolve it ?

Thanks

**Comment by nyeholt** [comment]
Are you calling $renderWith($ClassName) from the master template? Any reason you're not using $Layout (which will call the appropriate methods for rendering just the sub-template) instead? MemberProfilePage_Controller's `index()` action will render a different sub-template depending on context (ie if logged in or registering).

**Comment by liutaurasp** [comment]
Sorry about forgetting to close this, but it seems that the problem is in silverstripe not the module. Thanks for the reply.
